Handle key tuples pointing to invalid types
Previously, non-strings passed to resolve_config_path() would result in
a cryptic error such as:

    'dict' object has no attribute 'startswith'

That is now replaced with a more informative message:

    ERROR: Expected string but got dict at 'subsample' → '* (genome)' → 'samples' → '* (global)'.

The functions have been updated to pass the list of traversed keys down
through recursion calls so that a meaningful error message can be
constructed.