Validate build names
This prevents invalid build names from being evaluated for output.

Changes the error from:

    MissingInputException in rule all in file "/nextstrain/build/phylogenetic/Snakefile", line 26:
    Missing input files for rule all:
        affected files:
            auspice/measles_foo_tip-frequencies.json
            auspice/measles_foo.json

to:

    ERROR: The following names in 'builds' are not valid:

        foo

    Valid builds are:

        genome
        N450

Copied from wnv repo with some small adjustments.¹

¹ https://github.com/nextstrain/WNV/blob/009e0183863ccb532de2882af814d0c15a53dc64/phylogenetic/rules/config.smk#L1